import GeneralizedLatala.Coupled.Integrability

/-!
# Quadratic coupling estimate

The coupled time derivative, characteristic argument, Gronwall bound, and uniform quadratic estimate.

Main declarations:
- `logQuadraticMoment_differential_inequality`
- `gronwall_le_endpoint`
- `uniform_quadratic_coupling`

Dependencies:
- coupled trace algebra, integrability, and the independent endpoint bound

This file corresponds to the relevant part of `blueprint_latala.txt`.
-/

open MeasureTheory ProbabilityTheory Real BigOperators
open scoped ENNReal NNReal Topology

set_option maxHeartbeats 800000

namespace SpinGlass
namespace GeneralizedLatala

universe uΩ uι

variable {Ω : Type uΩ} [MeasureSpace Ω] [IsProbabilityMeasure (ℙ : Measure Ω)]

variable (N : ℕ) [NeZero N] (β h q : ℝ)
variable (sk : SKDisorder.{uΩ} (Ω := Ω) N β h)
variable (sim : SimpleDisorder.{uΩ} (Ω := Ω) N β q)

/-! ## Evaluate the raw differentiated integral -/

lemma coupledFreeEnergy_time_derivative_ibp_formula_workspace
    (hN : 0 < N)
    (hIndep : IndepFun sk.U sim.V (ℙ : Measure Ω))
    {t Λ : ℝ} (ht : t ∈ Set.Ioo (0 : ℝ) 1) :
    (∫ ω,
        fderiv ℝ
          (fun H : EnergySpace N =>
            coupledFreeEnergyDet (N := N) (q := q) H Λ)
          (H_t
            (N := N) (β := β) (h := h) (q := q)
            (sk := sk) (sim := sim) t ω)
          (dH_t
            (N := N) (β := β) (h := h) (q := q)
            (sk := sk) (sim := sim) t ω)
        ∂ℙ) =
      (1 / 2) *
        (bregmanRemainder sk.ξ β q 1 +
          tiltedBregman
            (N := N) (β := β) (h := h) (q := q)
            (sk := sk) (sim := sim) t (Λ / 2) -
          2 * coupledCrossBregman
            (N := N) (β := β) (h := h) (q := q)
            (sk := sk) (sim := sim) t (Λ / 2)) := by
  let T : Ω → ℝ := fun ω =>
    tiltedBregmanDet
      (N := N) (β := β) (h := h) (q := q) (sk := sk)
      (H_t
        (N := N) (β := β) (h := h) (q := q)
        (sk := sk) (sim := sim) t ω)
      (Λ / 2)
  let X : Ω → ℝ := fun ω =>
    coupledCrossBregmanDet
      (N := N) (β := β) (h := h) (q := q) (sk := sk)
      (H_t
        (N := N) (β := β) (h := h) (q := q)
        (sk := sk) (sim := sim) t ω)
      (Λ / 2)

  have hT : Integrable T ℙ := by
    simpa only [T] using
      integrable_tiltedBregmanDet_Ht_workspace
        (N := N) (β := β) (h := h) (q := q)
        (sk := sk) (sim := sim) t (Λ / 2)

  have hX : Integrable X ℙ := by
    simpa only [X] using
      integrable_coupledCrossBregmanDet_Ht_workspace
        (N := N) (β := β) (h := h) (q := q)
        (sk := sk) (sim := sim) t (Λ / 2)

  have hconst : Integrable (fun _ : Ω => bregmanRemainder sk.ξ β q 1) ℙ :=
    integrable_const _

  have hsum : Integrable (fun ω => bregmanRemainder sk.ξ β q 1 + T ω) ℙ :=
    hconst.add hT

  have htwiceX : Integrable (fun ω => 2 * X ω) ℙ :=
    hX.const_mul 2

  rw [coupledFreeEnergy_time_ibp_trace_workspace
    (N := N) (β := β) (h := h) (q := q)
    (sk := sk) (sim := sim) hIndep ht]

  rw [← integral_const_mul]

  rw [integral_congr_ae
    (ae_of_all _ fun ω =>
      coupled_trace_algebra_workspace
        (N := N) (β := β) (h := h) (q := q) (sk := sk) hN
        (H_t
          (N := N) (β := β) (h := h) (q := q)
          (sk := sk) (sim := sim) t ω)
        (Λ / 2))]

  rw [integral_const_mul]
  rw [integral_sub hsum htwiceX]
  rw [integral_add hconst hT]
  rw [integral_const]
  rw [integral_const_mul]

  simp only [probReal_univ, one_smul]

  change
    (1 / 2) *
        (bregmanRemainder sk.ξ β q 1 + (∫ ω, T ω ∂ℙ) - 2 * (∫ ω, X ω ∂ℙ)) =
      (1 / 2) *
        (bregmanRemainder sk.ξ β q 1 +
          tiltedBregman
            (N := N) (β := β) (h := h) (q := q)
            (sk := sk) (sim := sim) t (Λ / 2) -
          2 * coupledCrossBregman
            (N := N) (β := β) (h := h) (q := q)
            (sk := sk) (sim := sim) t (Λ / 2))

  simp only [T, X, tiltedBregman, coupledCrossBregman]

/-- Gaussian IBP formula for the time derivative of the coupled free energy.

The term `coupledCrossMoment` is the named annealed four-replica quantity generated by the
covariance trace.  Its nonnegativity is recorded separately in `coupledCrossMoment_nonneg`.

Use the same joint Gaussian model and the same call to
`gaussian_integration_by_parts_hilbert_cov_op` as in the ordinary pressure calculation.  Replace
`Φ` by the normalized logarithm of the coupled two-replica partition sum.  Its first derivative
is the tilted two-replica Gibbs average, while its second derivative is the corresponding Gibbs
covariance.  After applying `sk.cov_eq` and `sim.cov_eq`, introduce enough replicas to express
that covariance as the ordinary overlap term minus the nonnegative four-replica cross moment.
Finite configuration space again gives `ContDiff` and a constant moderate-growth bound for each
basis-direction test function.

Normalization note: `crossPairCenteredOverlapSq` is the average of the four cross-pair squares.
With that convention, the trace computation produces `-2 * coupledCrossMoment`, while the two
within-pair terms produce one copy of `tiltedCenteredOverlapSq`.  These coefficients should be
checked directly when the IBP proof is completed. -/
lemma coupledFreeEnergy_hasDerivAt_time_ibp
    (hN : 0 < N)
    (hIndep : IndepFun sk.U sim.V (ℙ : Measure Ω))
    {t Λ : ℝ} (ht : t ∈ Set.Ioo (0 : ℝ) 1) :
    HasDerivAt
      (fun s => coupledFreeEnergy
        (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) s Λ)
      ((1 / 2) *
        (bregmanRemainder sk.ξ β q 1 +
          tiltedBregman
            (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
            t (Λ / 2) -
          2 * coupledCrossBregman
            (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
            t (Λ / 2))) t := by
  rw [← coupledFreeEnergy_time_derivative_ibp_formula_workspace
    (N := N) (β := β) (h := h) (q := q)
    (sk := sk) (sim := sim) hN hIndep ht]

  exact coupledFreeEnergy_hasDerivAt_time_before_ibp
    (N := N) (β := β) (h := h) (q := q)
    (sk := sk) (sim := sim) ht

/-- The logarithmic quadratic moment is differentiable in the smart-path variable away from
the endpoints.

Proof route: subtract `pressure_derivative` from
`coupledFreeEnergy_hasDerivAt_time_ibp`, unfold `coupledExcess`, and rescale by `2N`.
The resulting derivative is retained existentially because only its inequality is used later. -/
lemma logQuadraticMoment_hasDerivAt_time
    (hN : 0 < N)
    (hIndep : IndepFun sk.U sim.V (ℙ : Measure Ω))
    {t coupling : ℝ} (ht : t ∈ Set.Ioo (0 : ℝ) 1) :
    ∃ dt : ℝ,
      HasDerivAt
        (fun s => logQuadraticMoment
          (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
          s coupling) dt t := by
  have hcoupled := coupledFreeEnergy_hasDerivAt_time_ibp
    (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
    hN hIndep (Λ := 2 * coupling) ht
  have hpressure := pressure_derivative
    (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
    hN hIndep ht
  have hexcess := hcoupled.sub hpressure
  have hscaled := hexcess.const_mul (2 * (N : ℝ))
  have hN0 : (N : ℝ) ≠ 0 := by exact_mod_cast (ne_of_gt hN)
  have hfun :
      (fun s => logQuadraticMoment
        (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
        s coupling) =
      fun s => (2 * (N : ℝ)) *
        (coupledFreeEnergy
            (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
            s (2 * coupling) -
          interpolatedPressure
            (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) s) := by
    funext s
    simp only [coupledFreeEnergy, coupledExcess, physicalLogQuadraticMoment]
    rw [show (2 : ℝ) * coupling / 2 = coupling by ring]
    calc
      logQuadraticMoment
          (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
          s coupling =
          (2 * (N : ℝ)) * (1 / (2 * (N : ℝ)) *
            logQuadraticMoment
              (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
              s coupling) := by field_simp [hN0]
      _ = _ := by ring
  rw [hfun]
  exact ⟨_, hscaled⟩

/-- Compatibility form of the explicit coupling derivative. -/
lemma deriv_logQuadraticMoment_coupling (t coupling : ℝ) :
    deriv
      (fun c => logQuadraticMoment
        (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
        t c) coupling =
      (N : ℝ) * tiltedCenteredOverlapSq
        (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
        t coupling :=
  (logQuadraticMoment_hasDerivAt_coupling_formula
    (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
    t coupling).deriv

/-- The first-order differential inequality behind the moving-coupling estimate.

Proof route: combine the two preceding derivative lemmas with the coupled Gaussian-IBP
identity.  Drop the nonnegative cross moment, cancel the ordinary pressure derivative, and use
the global Bregman bound to control the remaining covariance term by
`Γ * logQuadraticMoment / (2 * coupling)`. -/
lemma logQuadraticMoment_differential_inequality
    (hN : 0 < N)
    (hΓ0 : 0 ≤ Γ) (hΔ : BregmanBounds sk.ξ β q Γ)
    (hIndep : IndepFun sk.U sim.V (ℙ : Measure Ω))
    {t coupling : ℝ} (ht : t ∈ Set.Ioo (0 : ℝ) 1) (hcoupling : 0 < coupling) :
    deriv
        (fun s => logQuadraticMoment
          (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
          s coupling) t -
        (Γ / 2) * deriv
          (fun c => logQuadraticMoment
            (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
            t c) coupling
      ≤ (Γ / (2 * coupling)) *
          logQuadraticMoment
            (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
            t coupling := by
  let L : ℝ → ℝ := fun s => logQuadraticMoment
    (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) s coupling
  let V : ℝ := overlapVariance
    (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) t
  let T : ℝ := tiltedCenteredOverlapSq
    (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) t coupling
  let A : ℝ := tiltedBregman
    (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) t coupling
  let B : ℝ := bregmanAverage
    (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) t
  let X : ℝ := coupledCrossBregman
    (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) t coupling
  have hC := coupledFreeEnergy_hasDerivAt_time_ibp
    (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
    hN hIndep (t := t) (Λ := 2 * coupling) ht
  have hP := pressure_derivative
    (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
    hN hIndep ht
  have hdiff := hC.sub hP
  have hNr : (N : ℝ) ≠ 0 := by exact_mod_cast (Nat.ne_of_gt hN)
  have hfun : L = fun s => (2 * (N : ℝ)) *
      (coupledFreeEnergy
          (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
          s (2 * coupling) -
        interpolatedPressure
          (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) s) := by
    funext s
    simp only [L, coupledFreeEnergy, coupledExcess, physicalLogQuadraticMoment]
    rw [show (2 : ℝ) * coupling / 2 = coupling by ring]
    calc
      logQuadraticMoment N β h q sk sim s coupling =
          (2 * (N : ℝ)) * (1 / (2 * (N : ℝ)) *
            logQuadraticMoment N β h q sk sim s coupling) := by field_simp [hNr]
      _ = _ := by ring
  have hLraw := hdiff.const_mul (2 * (N : ℝ))
  change HasDerivAt
      (fun s => (2 * (N : ℝ)) *
        (coupledFreeEnergy
            (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
            s (2 * coupling) -
          interpolatedPressure
            (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) s))
      _ t at hLraw
  rw [← hfun] at hLraw
  have hL : HasDerivAt L
      ((N : ℝ) * (A + B - 2 * X)) t := by
    convert hLraw using 1 <;> simp [A, B, X] <;> ring
  have htime : deriv L t =
      (N : ℝ) * (A + B - 2 * X) := hL.deriv
  have hcouplingDeriv : deriv
      (fun c => logQuadraticMoment
        (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) t c)
      coupling = (N : ℝ) * T := by
    simpa [T] using deriv_logQuadraticMoment_coupling
      (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) t coupling
  have hX : 0 ≤ X := coupledCrossBregman_nonneg
    (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
    hN hΔ t coupling
  have hA : A ≤ (Γ / 2) * T := by
    dsimp only [A, T]
    rw [tiltedBregman, tiltedCenteredOverlapSq, ← integral_const_mul]
    apply integral_mono
    · exact integrable_tiltedBregmanDet_Ht_workspace N β h q sk sim t coupling
    · exact (integrable_tiltedCenteredOverlapSqDet_Ht_workspace N β h q sk sim t coupling).const_mul (Γ / 2)
    · intro ω
      exact tiltedBregman_le (N := N) (β := β) (h := h) (q := q) (sk := sk)
        hN hΔ _ coupling
  have hB : B ≤ (Γ / 2) * V :=
    bregmanAverage_le (N := N) (β := β) (h := h) (q := q)
      (sk := sk) (sim := sim) hN hΔ t
  have hleft : deriv L t - (Γ / 2) * ((N : ℝ) * T)
      ≤ (Γ / 2) * ((N : ℝ) * V) := by
    rw [htime]
    nlinarith [mul_nonneg (Nat.cast_nonneg N) hX,
      mul_le_mul_of_nonneg_left hA (Nat.cast_nonneg N),
      mul_le_mul_of_nonneg_left hB (Nat.cast_nonneg N)]
  have hscaled : coupling * (N : ℝ) * V ≤ logQuadraticMoment
      (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
      t coupling := by
    let g : Ω → ℝ := fun ω => coupling * N * gibbs_average_n_det N 2
      (H_t N β h q sk sim t ω) (centeredOverlapSq N q)
    have hg0 : 0 ≤ g := by
      exact fun ω =>
        mul_nonneg (mul_nonneg (le_of_lt hcoupling) (Nat.cast_nonneg _))
          (by
            apply Finset.sum_nonneg
            intro σs _
            exact mul_nonneg (sq_nonneg _)
              (Finset.prod_nonneg fun l _ => gibbs_pmf_nonneg
                (N := N) (H := H_t N β h q sk sim t ω) (σ := σs l)))
    have hlogint : Integrable (fun ω => Real.log
        (gibbs_average_n N β h q sk sim 2 t
          (fun σs => Real.exp (coupling * N * centeredOverlapSq N q σs)) ω)) ℙ := by
      have hi : Integrable (fun ω => gibbs_average_n N β h q sk sim 2 t
          (fun σs => Real.exp (coupling * N * centeredOverlapSq N q σs)) ω) ℙ := by
        apply SpinGlass.integrable_gibbs_average_n
      refine hi.mono'
        (Real.measurable_log.comp_aemeasurable hi.aemeasurable).aestronglyMeasurable ?_
      filter_upwards with ω
      rw [Real.norm_eq_abs, abs_of_nonneg (Real.log_nonneg (by
        simpa [tiltedReplicaPartition, tiltedReplicaPartitionDet, gibbs_average_n] using
          tiltedReplicaPartitionDet_one_le (N := N) (q := q)
            (H_t (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) t ω)
            (le_of_lt hcoupling)))]
      refine (Real.log_le_sub_one_of_pos ?_).trans (by linarith)
      simpa [tiltedReplicaPartition, tiltedReplicaPartitionDet, gibbs_average_n] using
        tiltedReplicaPartition_pos
          (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
          t coupling ω
    have hpoint : ∀ᵐ ω ∂ℙ, g ω ≤ Real.log
        (gibbs_average_n N β h q sk sim 2 t
          (fun σs => Real.exp (coupling * N * centeredOverlapSq N q σs)) ω) := by
      filter_upwards with ω
      exact scaled_centeredOverlapSq_le_log_gibbs_exp
        (N := N) (q := q)
        (H_t (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) t ω)
        coupling
    calc
      coupling * (N : ℝ) * V = ∫ ω, g ω ∂ℙ := by
        rw [MeasureTheory.integral_const_mul]
        rfl
      _ ≤ ∫ ω, Real.log
          (gibbs_average_n N β h q sk sim 2 t
            (fun σs => Real.exp (coupling * N * centeredOverlapSq N q σs)) ω) ∂ℙ :=
        MeasureTheory.integral_mono_of_nonneg (Filter.Eventually.of_forall hg0) hlogint hpoint
      _ = logQuadraticMoment N β h q sk sim t coupling := rfl
  rw [hcouplingDeriv]
  refine hleft.trans ?_
  have hv : (N : ℝ) * V ≤
      logQuadraticMoment
        (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
        t coupling / coupling := (le_div_iff₀ hcoupling).2 (by
          simpa [mul_comm, mul_left_comm, mul_assoc] using hscaled)
  calc
    (Γ / 2) * ((N : ℝ) * V)
        ≤ (Γ / 2) *
            (logQuadraticMoment
              (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
              t coupling / coupling) :=
      mul_le_mul_of_nonneg_left hv (div_nonneg hΓ0 (by norm_num))
    _ = (Γ / (2 * coupling)) *
          logQuadraticMoment
            (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
            t coupling := by field_simp

/-- Nonnegativity of the logarithmic quadratic moment for nonnegative exponential coupling. -/
lemma logQuadraticMoment_nonneg
    {t coupling : ℝ} (hcoupling : 0 ≤ coupling) :
    0 ≤ logQuadraticMoment
      (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
      t coupling := by
  rw [logQuadraticMoment]
  apply integral_nonneg
  intro ω
  apply Real.log_nonneg
  simpa [tiltedReplicaPartition, tiltedReplicaPartitionDet, gibbs_average_n] using
    tiltedReplicaPartitionDet_one_le
      (N := N) (q := q)
      (H_t (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) t ω)
      hcoupling

/-- Coupling followed backwards from time `u` to the independent endpoint. -/
noncomputable def characteristicCoupling (Γ coupling u s : ℝ) : ℝ :=
  coupling + (Γ / 2) * (u - s)

/-- The logarithmic moment restricted to the moving-coupling characteristic. -/
noncomputable def characteristicQuadraticMoment (Γ coupling u s : ℝ) : ℝ :=
  logQuadraticMoment
    (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
    s (characteristicCoupling Γ coupling u s)

/-- The moving coupling stays at least as large as its terminal value. -/
lemma characteristicCoupling_ge
    {Γ coupling u s : ℝ} (hΓ0 : 0 ≤ Γ) (hs : s ∈ Set.Icc (0 : ℝ) u) :
    coupling ≤ characteristicCoupling Γ coupling u s := by
  unfold characteristicCoupling
  have hus : 0 ≤ u - s := sub_nonneg.mpr hs.2
  linarith [mul_nonneg (div_nonneg hΓ0 zero_le_two) hus]

/-- A two-variable function is differentiable when its first partial derivative exists and its
second partial derivative exists nearby and is continuous. -/
private lemma hasFDerivAt_prod_of_continuous_snd
    (f g : ℝ × ℝ → ℝ) {t c a b : ℝ}
    (ht : HasDerivAt (fun x => f (x, c)) a t)
    (hc : ∀ p, HasDerivAt (fun y => f (p.1, y)) (g p) p.2)
    (hg : ContinuousAt g (t, c)) (hb : g (t, c) = b) :
    HasFDerivAt f
      (a • ContinuousLinearMap.fst ℝ ℝ ℝ + b • ContinuousLinearMap.snd ℝ ℝ ℝ)
      (t, c) := by
  rw [hasFDerivAt_iff_isLittleO_nhds_zero]
  rw [Asymptotics.isLittleO_iff]
  intro ε hε
  have htO := hasFDerivAt_iff_isLittleO_nhds_zero.mp ht.hasFDerivAt
  have htbound := htO.bound (half_pos hε)
  have htbound' : ∀ᶠ z : ℝ × ℝ in 𝓝 0,
      ‖f (t + z.1, c) - f (t, c) - a * z.1‖ ≤ (ε / 2) * ‖z.1‖ := by
    have hlim : Filter.Tendsto (fun z : ℝ × ℝ => z.1) (𝓝 0) (𝓝 0) :=
      continuous_fst.continuousAt
    filter_upwards [hlim.eventually htbound] with z hz
    simpa [ContinuousLinearMap.toSpanSingleton_apply, mul_comm] using hz
  have hge : ∀ᶠ p in 𝓝 (t, c), ‖g p - b‖ < ε / 2 := by
    have hnear := (Metric.tendsto_nhds.mp hg.tendsto) (ε / 2) (half_pos hε)
    filter_upwards [hnear] with p hp
    simpa [Real.dist_eq, hb] using hp
  obtain ⟨δ, hδ, hball⟩ := Metric.eventually_nhds_iff.mp hge
  have hsmall : ∀ᶠ z : ℝ × ℝ in 𝓝 0, ‖z‖ < δ := by
    exact Metric.eventually_nhds_iff.mpr ⟨δ, hδ, by
      intro z hz
      simpa [dist_zero_right] using hz⟩
  filter_upwards [htbound', hsmall] with z htime hzδ
  let x := t + z.1
  let y := c + z.2
  have hvertical : ‖f (x, y) - f (x, c) - b * z.2‖ ≤ (ε / 2) * ‖z.2‖ := by
    let k : ℝ → ℝ := fun w => f (x, w) - b * w
    have hkderiv (w : ℝ) : HasDerivAt k (g (x, w) - b) w := by
      change HasDerivAt ((fun y => f (x, y)) - fun y => b * y) (g (x, w) - b) w
      simpa only [id_eq, mul_one] using
        (hc (x, w)).sub ((hasDerivAt_id w).const_mul b)
    have hclose (w : ℝ) (hw : w ∈ Set.uIcc c y) : ‖g (x, w) - b‖ ≤ ε / 2 := by
      apply le_of_lt
      apply hball
      rw [Prod.dist_eq]
      have hx : dist x t ≤ ‖z‖ := by
        simp only [x, Real.dist_eq]
        simpa [Real.norm_eq_abs] using norm_fst_le z
      have hw' : dist w c ≤ ‖z‖ := by
        have : dist w c ≤ dist y c := by
          rcases le_total c y with hcy | hyc
          · rw [Set.uIcc_of_le hcy] at hw
            simp only [Real.dist_eq]
            rw [abs_of_nonneg (sub_nonneg.mpr hw.1),
              abs_of_nonneg (sub_nonneg.mpr hcy)]
            linarith [hw.2]
          · rw [Set.uIcc_of_ge hyc] at hw
            simp only [Real.dist_eq]
            rw [abs_of_nonpos (sub_nonpos.mpr hw.2),
              abs_of_nonpos (sub_nonpos.mpr hyc)]
            linarith [hw.1]
        calc
          dist w c ≤ dist y c := this
          _ = ‖z.2‖ := by simp [y, Real.norm_eq_abs]
          _ ≤ ‖z‖ := norm_snd_le z
      exact max_lt (lt_of_le_of_lt hx hzδ) (lt_of_le_of_lt hw' hzδ)
    have hmvt := (convex_uIcc c y).norm_image_sub_le_of_norm_hasDerivWithin_le
      (fun w hw => (hkderiv w).hasDerivWithinAt)
      (fun w hw => hclose w hw) Set.left_mem_uIcc Set.right_mem_uIcc
    convert hmvt using 1 <;> simp [k, x, y, Real.norm_eq_abs] <;> ring
  change ‖f ((t, c) + z) - f (t, c) -
    (a • ContinuousLinearMap.fst ℝ ℝ ℝ + b • ContinuousLinearMap.snd ℝ ℝ ℝ) z‖ ≤
      ε * ‖z‖
  have hsplit : f ((t, c) + z) - f (t, c) - (a * z.1 + b * z.2) =
      (f (x, y) - f (x, c) - b * z.2) +
      (f (t + z.1, c) - f (t, c) - a * z.1) := by
    change f (t + z.1, c + z.2) - f (t, c) - (a * z.1 + b * z.2) = _
    simp only [x, y]
    ring
  change ‖f ((t, c) + z) - f (t, c) - (a * z.1 + b * z.2)‖ ≤ ε * ‖z‖
  rw [hsplit]
  calc
    ‖(f (x, y) - f (x, c) - b * z.2) +
      (f (t + z.1, c) - f (t, c) - a * z.1)‖ ≤
        ‖f (x, y) - f (x, c) - b * z.2‖ +
          ‖f (t + z.1, c) - f (t, c) - a * z.1‖ := norm_add_le _ _
    _ ≤ (ε / 2) * ‖z.2‖ + (ε / 2) * ‖z.1‖ := add_le_add hvertical htime
    _ ≤ ε * ‖z‖ := by
      nlinarith [norm_fst_le z, norm_snd_le z]

/-- Joint continuity of the coupling partial derivative of the logarithmic moment. -/
private lemma couplingPartial_continuous : Continuous (fun p : ℝ × ℝ =>
    (N : ℝ) * tiltedCenteredOverlapSq
      (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) p.1 p.2) := by
  let G : ℝ × ℝ → Ω → ℝ := fun p ω => (N : ℝ) *
    tiltedCenteredOverlapSqDet (N := N) (q := q)
      (H_t (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) p.1 ω) p.2
  let B : ℝ := ∑ σs : ReplicaSpace N 2,
    (N : ℝ) * centeredOverlapSq N q σs
  have hHt_meas (r : ℝ) : Measurable (H_t
      (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) r) := by
    have hU := sk.hU.repr_measurable.const_smul (Real.sqrt r)
    have hV := sim.hV.repr_measurable.const_smul (Real.sqrt (1 - r))
    exact measurable_H_t_updated (N := N) (β := β) (h := h) (q := q)
      (sk := sk) (sim := sim) r
  have hG_meas (p : ℝ × ℝ) : AEStronglyMeasurable (G p) ℙ := by
    apply Measurable.aestronglyMeasurable
    dsimp only [G, tiltedCenteredOverlapSqDet]
    apply measurable_const.mul
    apply Measurable.div
    · unfold gibbs_average_n_det
      apply Finset.measurable_sum
      intro σs _
      apply measurable_const.mul
      apply Finset.measurable_prod
      intro l _
      exact (SpinGlass.contDiff_gibbs_pmf (N := N) (σ := σs l)).continuous.measurable.comp
        (hHt_meas p.1)
    · unfold tiltedReplicaPartitionDet gibbs_average_n_det
      apply Finset.measurable_sum
      intro σs _
      apply measurable_const.mul
      apply Finset.measurable_prod
      intro l _
      exact (SpinGlass.contDiff_gibbs_pmf (N := N) (σ := σs l)).continuous.measurable.comp
        (hHt_meas p.1)
  have hbound (p : ℝ × ℝ) (ω : Ω) : ‖G p ω‖ ≤ B := by
    simpa [G, B] using norm_tiltedLog_deriv_le
      (N := N) (q := q)
      (H_t (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) p.1 ω)
      p.2
  have hG_cont (ω : Ω) : Continuous (fun p => G p ω) := by
    have hHt : Continuous (fun p : ℝ × ℝ => H_t
        (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) p.1 ω) := by
      simp only [H_t, H_gauss]
      fun_prop
    dsimp only [G, tiltedCenteredOverlapSqDet]
    apply Continuous.mul continuous_const
    apply Continuous.div
    · unfold gibbs_average_n_det
      apply continuous_finset_sum
      intro σs _
      apply Continuous.mul
      · fun_prop
      · apply continuous_finset_prod
        intro l _
        exact (SpinGlass.contDiff_gibbs_pmf (N := N) (σ := σs l)).continuous.comp hHt
    · unfold tiltedReplicaPartitionDet gibbs_average_n_det
      apply continuous_finset_sum
      intro σs _
      apply Continuous.mul
      · fun_prop
      apply continuous_finset_prod
      intro l _
      exact (SpinGlass.contDiff_gibbs_pmf (N := N) (σ := σs l)).continuous.comp hHt
    · intro p
      exact (tiltedReplicaPartitionDet_pos
        (N := N) (q := q)
        (H_t (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) p.1 ω)
        p.2).ne'
  have hint : Continuous (fun p => ∫ ω, G p ω ∂ℙ) := by
    rw [continuous_iff_continuousAt]
    intro p
    apply MeasureTheory.continuousAt_of_dominated
    · exact Filter.Eventually.of_forall hG_meas
    · exact Filter.Eventually.of_forall fun r => ae_of_all _ fun ω => hbound r ω
    · exact integrable_const B
    · exact ae_of_all _ fun ω => (hG_cont ω).continuousAt
  have heq : (fun p => ∫ ω, G p ω ∂ℙ) = fun p : ℝ × ℝ =>
      (N : ℝ) * tiltedCenteredOverlapSq
        (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) p.1 p.2 := by
    funext p
    simp only [G, tiltedCenteredOverlapSq, MeasureTheory.integral_const_mul]
  rwa [heq] at hint

/-- The logarithmic moment is jointly differentiable in time and coupling away from the time
endpoints. -/
lemma logQuadraticMoment_differentiableAt_two_variables
    (hN : 0 < N) (hIndep : IndepFun sk.U sim.V (ℙ : Measure Ω))
    {t coupling : ℝ} (ht : t ∈ Set.Ioo (0 : ℝ) 1) :
    DifferentiableAt ℝ (fun p : ℝ × ℝ => logQuadraticMoment
      (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) p.1 p.2)
      (t, coupling) := by
  obtain ⟨dt, htime⟩ := logQuadraticMoment_hasDerivAt_time
    (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
    hN hIndep ht (coupling := coupling)
  let g : ℝ × ℝ → ℝ := fun p => (N : ℝ) * tiltedCenteredOverlapSq
    (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) p.1 p.2
  have hcoupling (p : ℝ × ℝ) : HasDerivAt
      (fun y => logQuadraticMoment
        (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) p.1 y)
      (g p) p.2 := by
    simpa [g] using logQuadraticMoment_hasDerivAt_coupling_formula
      (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) p.1 p.2
  exact (hasFDerivAt_prod_of_continuous_snd
    (f := fun p : ℝ × ℝ => logQuadraticMoment
      (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) p.1 p.2)
    (g := g) htime hcoupling (by
      simpa [g] using (couplingPartial_continuous
        (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)).continuousAt)
    rfl).differentiableAt

/-- Chain rule and PDE inequality along the characteristic.

Proof route: obtain `HasDerivAt` in both variables, note that the coupling path has derivative
`-Γ / 2`, and use `HasDerivAt.scomp` or the two-variable Fréchet chain rule.  Apply
`logQuadraticMoment_differential_inequality`; then use `characteristicCoupling_ge` and
nonnegativity of the logarithmic moment to replace the moving denominator by `coupling`. -/
lemma characteristicQuadraticMoment_differential_inequality
    (hN : 0 < N)
    (hΓ0 : 0 ≤ Γ) (hΔ : BregmanBounds sk.ξ β q Γ)
    (hIndep : IndepFun sk.U sim.V (ℙ : Measure Ω))
    {coupling u s : ℝ} (hcoupling : 0 < coupling)
    (hu : u ∈ Set.Icc (0 : ℝ) 1) (hs : s ∈ Set.Ioo (0 : ℝ) u) :
    ∃ d : ℝ,
      HasDerivAt
        (characteristicQuadraticMoment
          (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
          Γ coupling u) d s ∧
      d ≤ (Γ / (2 * coupling)) *
        characteristicQuadraticMoment
          (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
          Γ coupling u s := by
  let c : ℝ := characteristicCoupling Γ coupling u s
  let L : ℝ × ℝ → ℝ := fun p => logQuadraticMoment
    (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) p.1 p.2
  have hs01 : s ∈ Set.Ioo (0 : ℝ) 1 := ⟨hs.1, lt_of_lt_of_le hs.2 hu.2⟩
  have hcge : coupling ≤ c := characteristicCoupling_ge
    (Γ := Γ) (coupling := coupling) (u := u) (s := s) hΓ0
    ⟨le_of_lt hs.1, le_of_lt hs.2⟩
  have hc : 0 < c := lt_of_lt_of_le hcoupling hcge
  obtain ⟨dt, hdt⟩ := logQuadraticMoment_hasDerivAt_time
    (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
    hN hIndep hs01 (coupling := c)
  have hdc := logQuadraticMoment_hasDerivAt_coupling_formula
    (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) s c
  have hL : DifferentiableAt ℝ L (s, c) := by
    simpa [L] using logQuadraticMoment_differentiableAt_two_variables
      (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
      hN hIndep hs01 (coupling := c)
  have hpath : HasDerivAt
      (fun r : ℝ => (r, characteristicCoupling Γ coupling u r))
      (1, -(Γ / 2)) s := by
    have hcpath := (hasDerivAt_const s coupling).add
      (((hasDerivAt_const s u).sub (hasDerivAt_id s)).const_mul (Γ / 2))
    have hcoeff : 0 + (Γ / 2) * (0 - 1) = -(Γ / 2) := by ring
    rw [hcoeff] at hcpath
    have hcpath' : HasDerivAt
        (fun r => characteristicCoupling Γ coupling u r) (-(Γ / 2)) s := by
      apply hcpath.congr_of_eventuallyEq
      filter_upwards with r
      simp [characteristicCoupling]
    exact (hasDerivAt_id s).prodMk hcpath'
  have hdiag := hL.hasFDerivAt.comp_hasDerivAt s hpath
  have htimeComp := hL.hasFDerivAt.comp_hasDerivAt s
    ((hasDerivAt_id s).prodMk (hasDerivAt_const s c))
  have hcouplingComp := hL.hasFDerivAt.comp_hasDerivAt c
    ((hasDerivAt_const c s).prodMk (hasDerivAt_id c))
  have htimeEval : fderiv ℝ L (s, c) (1, 0) = dt := by
    exact htimeComp.unique (by simpa [L, Function.comp_def] using hdt)
  have hcouplingEval : fderiv ℝ L (s, c) (0, 1) =
      (N : ℝ) * tiltedCenteredOverlapSq
        (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) s c := by
    exact hcouplingComp.unique (by simpa [L, Function.comp_def] using hdc)
  let dc : ℝ := (N : ℝ) * tiltedCenteredOverlapSq
    (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) s c
  let d : ℝ := dt - (Γ / 2) * dc
  have hdiag' : HasDerivAt
      (characteristicQuadraticMoment
        (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
        Γ coupling u) d s := by
    have heval : fderiv ℝ L (s, c) (1, -(Γ / 2)) = d := by
      rw [show (1, -(Γ / 2)) =
          ((1 : ℝ), (0 : ℝ)) + (-(Γ / 2)) • ((0 : ℝ), (1 : ℝ)) by
        ext <;> simp]
      rw [map_add, map_smul, htimeEval, hcouplingEval]
      simp only [smul_eq_mul, dc, d]
      ring
    rw [heval] at hdiag
    change HasDerivAt
      (L ∘ fun r => (r, characteristicCoupling Γ coupling u r)) d s
    simpa [c] using hdiag
  refine ⟨d, hdiag', ?_⟩
  have hpde := logQuadraticMoment_differential_inequality
    (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
    hN hΓ0 hΔ hIndep hs01 hc
  have hdtDeriv : deriv (fun r => logQuadraticMoment
      (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) r c) s = dt := hdt.deriv
  have hdcDeriv : deriv (fun z => logQuadraticMoment
      (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) s z) c = dc := by
    simpa [dc] using hdc.deriv
  rw [hdtDeriv, hdcDeriv] at hpde
  have hmoment : 0 ≤ logQuadraticMoment
      (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) s c :=
    logQuadraticMoment_nonneg
      (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
      (le_of_lt hc)
  have hcoef : Γ / (2 * c) ≤ Γ / (2 * coupling) := by
    rw [div_le_div_iff₀ (by positivity : 0 < 2 * c)
      (by positivity : 0 < 2 * coupling)]
    nlinarith
  dsimp only [d]
  refine hpde.trans ?_
  simpa [characteristicQuadraticMoment, c] using
    mul_le_mul_of_nonneg_right hcoef hmoment

/-- Continuity on the closed characteristic, including both endpoints.

Proof route: use the same dominated-convergence argument as
`interpolatedPressure_continuousOn`.  The finite replica sum is continuous jointly in time and
coupling.  On the compact characteristic its exponential tilt is uniformly bounded, which
provides an integrable disorder-independent dominator. -/
lemma characteristicQuadraticMoment_continuousOn
    {Γ coupling u : ℝ} (hΓ0 : 0 ≤ Γ) (hcoupling : 0 < coupling)
    (hu : u ∈ Set.Icc (0 : ℝ) 1) :
    ContinuousOn
      (characteristicQuadraticMoment
        (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
        Γ coupling u) (Set.Icc (0 : ℝ) u) := by
  classical
  let K : ℝ := ∑ σs : ReplicaSpace N 2,
    Real.exp ((coupling + Γ / 2) * (N : ℝ) * centeredOverlapSq N q σs)
  unfold characteristicQuadraticMoment logQuadraticMoment
  apply MeasureTheory.continuousOn_of_dominated (bound := fun _ : Ω => K)
  · intro s _
    have hHt_meas : Measurable
        (H_t (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) s) := by
      have hU := sk.hU.repr_measurable.const_smul (Real.sqrt s)
      have hV := sim.hV.repr_measurable.const_smul (Real.sqrt (1 - s))
      exact measurable_H_t_updated (N := N) (β := β) (h := h) (q := q)
        (sk := sk) (sim := sim) s
    have hpart : Measurable fun w =>
        gibbs_average_n
          (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
          2 s
          (fun σs => Real.exp
            (characteristicCoupling Γ coupling u s * (N : ℝ) *
              centeredOverlapSq N q σs)) w := by
      unfold gibbs_average_n gibbs_average_n_det
      apply Finset.measurable_sum
      intro σs _
      apply measurable_const.mul
      apply Finset.measurable_prod
      intro l _
      exact (SpinGlass.contDiff_gibbs_pmf (N := N) (σ := σs l)).continuous.measurable.comp
        hHt_meas
    exact hpart.log.aestronglyMeasurable
  · intro s hs
    filter_upwards with w
    let c := characteristicCoupling Γ coupling u s
    have hc0 : 0 ≤ c :=
      le_trans (le_of_lt hcoupling)
        (characteristicCoupling_ge (Γ := Γ) (coupling := coupling) hΓ0 hs)
    have hcu : c ≤ coupling + Γ / 2 := by
      dsimp only [c, characteristicCoupling]
      have hus : u - s ≤ 1 := by linarith [hu.2, hs.1]
      nlinarith
    have hpart_one : 1 ≤
        gibbs_average_n
          (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
          2 s (fun σs => Real.exp
            (c * (N : ℝ) * centeredOverlapSq N q σs)) w := by
      change 1 ≤ tiltedReplicaPartitionDet (N := N) (q := q)
        (H_t (N := N) (β := β) (h := h) (q := q)
          (sk := sk) (sim := sim) s w) c
      exact tiltedReplicaPartitionDet_one_le (N := N) (q := q)
        (H_t (N := N) (β := β) (h := h) (q := q)
          (sk := sk) (sim := sim) s w) hc0
    have hpart_le :
        gibbs_average_n
          (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
          2 s (fun σs => Real.exp
            (c * (N : ℝ) * centeredOverlapSq N q σs)) w ≤ K := by
      calc
        gibbs_average_n
              (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
              2 s (fun σs => Real.exp
                (c * (N : ℝ) * centeredOverlapSq N q σs)) w
            ≤ |gibbs_average_n
                (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
                2 s (fun σs => Real.exp
                  (c * (N : ℝ) * centeredOverlapSq N q σs)) w| := le_abs_self _
        _ ≤ ∑ σs : ReplicaSpace N 2,
              |Real.exp (c * (N : ℝ) * centeredOverlapSq N q σs)| :=
          abs_gibbs_average_n_le
            (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
            (n := 2) (t := s)
            (f := fun σs => Real.exp
              (c * (N : ℝ) * centeredOverlapSq N q σs)) (w := w)
        _ ≤ K := by
          dsimp only [K]
          apply Finset.sum_le_sum
          intro σs _
          rw [abs_of_pos (Real.exp_pos _)]
          apply Real.exp_le_exp.mpr
          exact mul_le_mul_of_nonneg_right
            (mul_le_mul_of_nonneg_right hcu (Nat.cast_nonneg N)) (sq_nonneg _)
    rw [Real.norm_eq_abs, abs_of_nonneg (Real.log_nonneg hpart_one)]
    exact (Real.log_le_self (le_trans zero_le_one hpart_one)).trans hpart_le
  · exact integrable_const K
  · filter_upwards with w
    have hHt : Continuous fun s =>
        H_t (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim) s w := by
      simp only [H_t, H_gauss]
      fun_prop
    have hc : Continuous fun s => characteristicCoupling Γ coupling u s := by
      unfold characteristicCoupling
      fun_prop
    have hpart : Continuous fun s =>
        gibbs_average_n
          (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
          2 s (fun σs => Real.exp
            (characteristicCoupling Γ coupling u s * (N : ℝ) *
              centeredOverlapSq N q σs)) w := by
      unfold gibbs_average_n gibbs_average_n_det
      apply continuous_finset_sum
      intro σs _
      apply Continuous.mul
      · exact (Real.continuous_exp.comp
          ((hc.mul continuous_const).mul continuous_const))
      · apply continuous_finset_prod
        intro l _
        exact (SpinGlass.contDiff_gibbs_pmf (N := N) (σ := σs l)).continuous.comp hHt
    exact (hpart.log fun s => (tiltedReplicaPartition_pos
      (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
      s (characteristicCoupling Γ coupling u s) w).ne').continuousOn

/-- One-dimensional integrating-factor estimate with explicit endpoint hypotheses.

Proof route: multiply `f` by `exp (-a * s)`, use the product rule to show that the result has
nonpositive derivative on `Ioo 0 u`, apply monotonicity on `Icc 0 u`, and rearrange. -/
lemma gronwall_le_endpoint
    {f : ℝ → ℝ} {a u : ℝ} (hu : 0 ≤ u)
    (hcont : ContinuousOn f (Set.Icc (0 : ℝ) u))
    (hderiv : ∀ s ∈ Set.Ioo (0 : ℝ) u, ∃ d : ℝ,
      HasDerivAt f d s ∧ d ≤ a * f s) :
    f u ≤ Real.exp (a * u) * f 0 := by
  let g : ℝ → ℝ := fun s => Real.exp (-a * s) * f s
  have hgcont : ContinuousOn g (Set.Icc (0 : ℝ) u) := by
    exact (Real.continuous_exp.comp
      ((continuous_const : Continuous (fun _ : ℝ => -a)).mul continuous_id)).continuousOn.mul hcont
  have hganti : AntitoneOn g (Set.Icc (0 : ℝ) u) := by
    refine antitoneOn_of_deriv_nonpos (convex_Icc (0 : ℝ) u) hgcont ?_ ?_
    · intro s hs
      rw [interior_Icc] at hs
      obtain ⟨d, hfd, hd⟩ := hderiv s hs
      have hinner : HasDerivAt (fun x : ℝ => -a * x) (-a) s := by
        simpa only [id_eq, mul_one] using (hasDerivAt_id s).const_mul (-a)
      have hexp : HasDerivAt (fun x : ℝ => Real.exp (-a * x))
          (Real.exp (-a * s) * (-a)) s :=
        (Real.hasDerivAt_exp (-a * s)).comp s hinner
      exact (hexp.mul hfd).differentiableAt.differentiableWithinAt
    · intro s hs
      rw [interior_Icc] at hs
      obtain ⟨d, hfd, hd⟩ := hderiv s hs
      have hgderiv : HasDerivAt g
          (Real.exp (-a * s) * (d - a * f s)) s := by
        have hinner : HasDerivAt (fun x : ℝ => -a * x) (-a) s := by
          simpa only [id_eq, mul_one] using (hasDerivAt_id s).const_mul (-a)
        have hexp : HasDerivAt (fun x : ℝ => Real.exp (-a * x))
            (Real.exp (-a * s) * (-a)) s :=
          (Real.hasDerivAt_exp (-a * s)).comp s hinner
        change HasDerivAt ((fun x : ℝ => Real.exp (-a * x)) * f) _ s
        exact (hexp.mul hfd).congr_deriv (by ring)
      rw [hgderiv.deriv]
      exact mul_nonpos_of_nonneg_of_nonpos (Real.exp_nonneg _) (sub_nonpos.mpr hd)
  have hgu : g u ≤ g 0 := hganti (Set.left_mem_Icc.mpr hu) (Set.right_mem_Icc.mpr hu) hu
  dsimp only [g] at hgu
  have hexp : 0 < Real.exp (a * u) := Real.exp_pos _
  have hmul := mul_le_mul_of_nonneg_left hgu hexp.le
  have hinv : Real.exp (a * u) * Real.exp (-a * u) = 1 := by
    rw [← Real.exp_add]
    simp
  calc
    f u = Real.exp (a * u) * (Real.exp (-a * u) * f u) := by rw [← mul_assoc, hinv, one_mul]
    _ ≤ Real.exp (a * u) * (Real.exp (-a * 0) * f 0) := hmul
    _ = Real.exp (a * u) * f 0 := by simp

/-- Characteristic (Grönwall) estimate for the logarithmic quadratic moment.

This theorem is now only the assembly of the characteristic regularity, its differential
inequality, and the generic integrating-factor lemma. -/
lemma logQuadraticMoment_characteristic
    (hN : 0 < N)
    (hΓ0 : 0 ≤ Γ) (hΔ : BregmanBounds sk.ξ β q Γ)
    (hIndep : IndepFun sk.U sim.V (ℙ : Measure Ω))
    {coupling u : ℝ} (hcoupling : 0 < coupling)
    (hu : u ∈ Set.Icc (0 : ℝ) 1) :
    logQuadraticMoment
        (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
        u coupling
      ≤ Real.exp (Γ * u / (2 * coupling)) *
        logQuadraticMoment
          (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
          0 ((2 * coupling + Γ * u) / 2) := by
  have hgronwall := gronwall_le_endpoint
    (f := characteristicQuadraticMoment
      (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
      Γ coupling u)
    (a := Γ / (2 * coupling)) hu.1
    (characteristicQuadraticMoment_continuousOn
      (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
      hΓ0 hcoupling hu)
    (fun s hs => characteristicQuadraticMoment_differential_inequality
      (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
      hN hΓ0 hΔ hIndep hcoupling hu hs)
  simp only [characteristicQuadraticMoment, characteristicCoupling] at hgronwall ⊢
  convert hgronwall using 1 <;> ring

/-- Positivity of the coupling scale in the improved region. -/
lemma lambdaStar_pos
    (hq0 : 0 ≤ q) (hq1 : q < 1) (hρ : rho Γ q < 1) :
    0 < lambdaStar Γ q := by
  have hk : 0 < kappa q := kappa_pos hq0 hq1
  have hΓ : Γ < (kappa q)⁻¹ := by
    rw [inv_eq_one_div]
    exact (lt_div_iff₀ hk).2 (by simpa [rho] using hρ)
  simp only [lambdaStar]
  linarith

/-- The parameter `rho` is nonnegative on the physical range of `q`. -/
lemma rho_nonneg
    (hΓ0 : 0 ≤ Γ) (hq0 : 0 ≤ q) (hq1 : q < 1) :
    0 ≤ rho Γ q := by
  exact mul_nonneg hΓ0 (le_of_lt (kappa_pos hq0 hq1))

/-- The coupling scale written in terms of the distance to the boundary `rho = 1`. -/
lemma lambdaStar_eq_one_sub_rho_div
    (hq0 : 0 ≤ q) (hq1 : q < 1) :
    lambdaStar Γ q = (1 - rho Γ q) / (4 * kappa q) := by
  have hk0 : kappa q ≠ 0 := ne_of_gt (kappa_pos hq0 hq1)
  simp only [lambdaStar, rho]
  field_simp [hk0]

/-- Algebraic identity for the moving coupling used in the quadratic interpolation. -/
lemma kappa_mul_movingCoupling
    (hq0 : 0 ≤ q) (hq1 : q < 1) (t : ℝ) :
    kappa q * (2 * lambdaStar Γ q + Γ * t) =
      (1 - rho Γ q) / 2 + rho Γ q * t := by
  have hk0 : kappa q ≠ 0 := ne_of_gt (kappa_pos hq0 hq1)
  simp only [lambdaStar, rho]
  field_simp [hk0]
  ring

/-- The moving coupling remains in the range allowed by the endpoint estimate. -/
lemma movingCoupling_admissible
    (hΓ0 : 0 ≤ Γ) (hq0 : 0 ≤ q) (hq1 : q < 1) (hρ : rho Γ q < 1)
    {t : ℝ} (ht : t ∈ Set.Icc (0 : ℝ) 1) :
    kappa q * (2 * lambdaStar Γ q + Γ * t) < 1 := by
  rw [kappa_mul_movingCoupling (Γ := Γ) (q := q) hq0 hq1]
  have hρ0 : 0 ≤ rho Γ q := rho_nonneg (Γ := Γ) (q := q) hΓ0 hq0 hq1
  have hmul : rho Γ q * t ≤ rho Γ q :=
    mul_le_of_le_one_right hρ0 ht.2
  linarith

/-- Quantitative slack in the endpoint admissibility inequality. -/
lemma movingCoupling_gap
    (hΓ0 : 0 ≤ Γ) (hq0 : 0 ≤ q) (hq1 : q < 1)
    {t : ℝ} (ht : t ∈ Set.Icc (0 : ℝ) 1) :
    (1 - rho Γ q) / 2 ≤
      1 - kappa q * (2 * lambdaStar Γ q + Γ * t) := by
  rw [kappa_mul_movingCoupling (Γ := Γ) (q := q) hq0 hq1]
  have hρ0 : 0 ≤ rho Γ q := rho_nonneg (Γ := Γ) (q := q) hΓ0 hq0 hq1
  have hmul : rho Γ q * t ≤ rho Γ q :=
    mul_le_of_le_one_right hρ0 ht.2
  linarith

/-- The moving coupling is strictly positive throughout the interpolation interval. -/
lemma movingCoupling_pos
    (hΓ0 : 0 ≤ Γ) (hq0 : 0 ≤ q) (hq1 : q < 1) (hρ : rho Γ q < 1)
    {t : ℝ} (ht : t ∈ Set.Icc (0 : ℝ) 1) :
    0 < 2 * lambdaStar Γ q + Γ * t := by
  have hlambda : 0 < lambdaStar Γ q :=
    lambdaStar_pos (Γ := Γ) (q := q) hq0 hq1 hρ
  have hΓt : 0 ≤ Γ * t := mul_nonneg hΓ0 ht.1
  linarith

/-- Exact exponent appearing after applying Grönwall's inequality. -/
lemma gamma_div_two_lambdaStar
    (hq0 : 0 ≤ q) (hq1 : q < 1) (hρ : rho Γ q < 1) :
    Γ / (2 * lambdaStar Γ q) =
      2 * rho Γ q / (1 - rho Γ q) := by
  have hk0 : kappa q ≠ 0 := ne_of_gt (kappa_pos hq0 hq1)
  have hgap0 : 1 - rho Γ q ≠ 0 := ne_of_gt (sub_pos.mpr hρ)
  rw [lambdaStar_eq_one_sub_rho_div (Γ := Γ) (q := q) hq0 hq1]
  simp only [rho]
  field_simp [hk0, hgap0]
  ring

/-- The explicit constant in the quadratic estimate is positive in the improved region. -/
lemma quadraticConstant_pos
    (hΓ0 : 0 ≤ Γ) (hq0 : 0 ≤ q) (hq1 : q < 1) (hρ : rho Γ q < 1) :
    0 < quadraticConstant Γ q := by
  have hρ0 : 0 ≤ rho Γ q := rho_nonneg (Γ := Γ) (q := q) hΓ0 hq0 hq1
  have hgap : 0 < 1 - rho Γ q := sub_pos.mpr hρ
  have hratio : 1 < 2 / (1 - rho Γ q) := by
    rw [lt_div_iff₀ hgap]
    linarith
  have hlog : 0 < Real.log (2 / (1 - rho Γ q)) := Real.log_pos hratio
  exact mul_pos (mul_pos (by norm_num) (Real.exp_pos _)) hlog

/-- Endpoint control for the moving coupling, already simplified to the uniform bound. -/
lemma endpoint_movingCoupling
    (hN : 0 < N) (hβ0 : 0 ≤ β) (hΓ0 : 0 ≤ Γ)
    (hq0 : 0 ≤ q) (hq1 : q < 1)
    (hfp : IsRSFixedPoint β h q) (hρ : rho Γ q < 1)
    {t : ℝ} (ht : t ∈ Set.Icc (0 : ℝ) 1) :
    logQuadraticMoment
        (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
        0 ((2 * lambdaStar Γ q + Γ * t) / 2)
      ≤ (1 / 2) * Real.log (2 / (1 - rho Γ q)) := by
  let Λ : ℝ := 2 * lambdaStar Γ q + Γ * t
  have hΛ0 : 0 ≤ Λ := le_of_lt
    (movingCoupling_pos (Γ := Γ) (q := q) hΓ0 hq0 hq1 hρ ht)
  have hΛ : kappa q * Λ < 1 :=
    movingCoupling_admissible (Γ := Γ) (q := q) hΓ0 hq0 hq1 hρ ht
  have hend := endpoint_quadratic
    (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
    hN hβ0 hq0 hq1 hfp hΛ0 hΛ
  have hgap : (1 - rho Γ q) / 2 ≤ 1 - kappa q * Λ :=
    movingCoupling_gap (Γ := Γ) (q := q) hΓ0 hq0 hq1 ht
  have hdenom : 0 < 1 - kappa q * Λ := sub_pos.mpr hΛ
  have hρgap : 0 < 1 - rho Γ q := sub_pos.mpr hρ
  have hratio : 1 / (1 - kappa q * Λ) ≤ 2 / (1 - rho Γ q) := by
    rw [div_le_div_iff₀ hdenom hρgap]
    linarith
  have hlog :
      Real.log (1 / (1 - kappa q * Λ)) ≤
        Real.log (2 / (1 - rho Γ q)) := by
    exact Real.log_le_log (by positivity) hratio
  exact hend.trans (mul_le_mul_of_nonneg_left hlog (by norm_num))

/-- The moving-coupling estimate obtained by following the characteristic
`Λ(s) = 2 * coupling + Γ * (t - s)` in the coupled interpolation. -/
lemma logQuadraticMoment_le_endpoint
    (hN : 0 < N)
    (hΓ0 : 0 ≤ Γ) (hΔ : BregmanBounds sk.ξ β q Γ)
    (hIndep : IndepFun sk.U sim.V (ℙ : Measure Ω))
    {coupling t : ℝ} (hcoupling : 0 < coupling)
    (ht : t ∈ Set.Icc (0 : ℝ) 1) :
    logQuadraticMoment
        (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
        t coupling
      ≤ Real.exp (Γ * t / (2 * coupling)) *
        logQuadraticMoment
          (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
          0 ((2 * coupling + Γ * t) / 2) := by
  exact logQuadraticMoment_characteristic
    (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
    hN hΓ0 hΔ hIndep hcoupling ht

/-
Proposition `quadratic-estimate` from the blueprint.
-/
theorem uniform_quadratic_coupling
    (hN : 0 < N) (hβ0 : 0 ≤ β) (hΓ0 : 0 ≤ Γ)
    (hq0 : 0 ≤ q) (hq1 : q < 1)
    (hfp : IsRSFixedPoint β h q)
    (hΔ : BregmanBounds sk.ξ β q Γ) (hρ : rho Γ q < 1)
    (hIndep : IndepFun sk.U sim.V (ℙ : Measure Ω))
    {t : ℝ} (ht : t ∈ Set.Icc (0 : ℝ) 1) :
    logQuadraticMoment
        (N := N) (β := β) (h := h) (q := q) (sk := sk) (sim := sim)
        t (lambdaStar Γ q)
      ≤ quadraticConstant Γ q := by
  -- Apply `logQuadraticMoment_le_endpoint` with coupling `lambdaStar Γ q`.
  have h_logQuadraticMoment_le_endpoint : logQuadraticMoment N β h q sk sim t (lambdaStar Γ q) ≤ Real.exp (Γ * t / (2 * lambdaStar Γ q)) * logQuadraticMoment N β h q sk sim 0 ((2 * lambdaStar Γ q + Γ * t) / 2) := by
    apply logQuadraticMoment_le_endpoint;
    · exact hN;
    · exact hΓ0;
    · exact hΔ;
    · exact hIndep;
    · exact lambdaStar_pos (Γ := Γ) (q := q) hq0 hq1 hρ
    · exact ht;
  have h_logQuadraticMoment_le_endpoint : logQuadraticMoment N β h q sk sim 0 ((2 * lambdaStar Γ q + Γ * t) / 2) ≤ (1 / 2) * Real.log (2 / (1 - rho Γ q)) := by
    exact endpoint_movingCoupling (N := N) (β := β) (h := h) (q := q)
      (sk := sk) (sim := sim) hN hβ0 hΓ0 hq0 hq1 hfp hρ ht
  refine' le_trans ‹_› ( le_trans ( mul_le_mul_of_nonneg_left h_logQuadraticMoment_le_endpoint ( Real.exp_nonneg _ ) ) _ );
  -- Simplify the exponent using `Γ / (2 * lambdaStar Γ q) = 2ρ / (1 - ρ)`.
  have h_exp_simplified : Real.exp (Γ * t / (2 * lambdaStar Γ q)) ≤ Real.exp (2 * rho Γ q / (1 - rho Γ q)) := by
    have h_exp_bound : Γ / (2 * lambdaStar Γ q) = 2 * rho Γ q / (1 - rho Γ q) :=
      gamma_div_two_lambdaStar (Γ := Γ) (q := q) hq0 hq1 hρ
    exact Real.exp_le_exp.mpr (by rw [← h_exp_bound]; exact div_le_div_of_nonneg_right (mul_le_of_le_one_right hΓ0 ht.2) (mul_nonneg zero_le_two (le_of_lt (lambdaStar_pos (Γ := Γ) (q := q) hq0 hq1 hρ))))
  refine' le_trans ( mul_le_mul_of_nonneg_right h_exp_simplified ( mul_nonneg ( by norm_num ) ( Real.log_nonneg _ ) ) ) _;
  · rw [le_div_iff₀] <;>
      linarith [rho_nonneg (Γ := Γ) (q := q) hΓ0 hq0 hq1]
  · unfold quadraticConstant; ring_nf; norm_num;


end GeneralizedLatala
end SpinGlass
