import Lemmas.GTbound.Basic
open MeasureTheory
#check integral_map
#check MeasureTheory.integral_map
#check Equiv.piProd
#check Equiv.piCongrRight
#check Fintype.prod_sum
#check MeasureTheory.integral_fintype_prod_eq_prod
#check MeasureTheory.integral_fintype_prod_eq_pow
#check MeasureTheory.integral_comp_eval
#check EuclideanSpace.basisFun
#check PiLp.basisFun
#check EuclideanSpace.single
#check ProbabilityTheory.iIndepFun_pi
#check PhysLean.Probability.GaussianIBP.IsGaussianHilbert
#check ContinuousLinearMap.proj
#check PiLp.continuousLinearMap_apply
#check EuclideanSpace.proj
#check HasFDerivAt.div
#check HasFDerivAt.inv
#check HasFDerivAt.mul
#check Finset.sum_pos'
#check ProbabilityTheory.IsCenteredGaussianRV
#check SpinGlass.GeneralizedLatala.gaussianProduct_eval_gaussian
#check SpinGlass.GeneralizedLatala.gaussianProduct_eval_law
#check WithLp.toLp
#print ProbabilityTheory.IsCenteredGaussianRV
