import Lemmas.Cavity.cavity_interpolation

#check Fin.castAdd
#check Fin.castLE
#check Fin.natAdd
#check Fin.addCases
#check finSumFinEquiv
#check Fin.append
#check Equiv.piCongrLeft
#check Fintype.sum_equiv
#check Fin.prod_univ_succ
#check Fin.sum_univ_succ
#check Fin.prod_univ_add
#check Fin.sum_univ_add
#check Fin.append_left
#check Fin.append_right
#check Fin.append_right'
#check Fin.append_left'
#check Equiv.sumPiEquivProdPi
#check Equiv.piSumEquiv
#check Equiv.piFinTwo
#check Equiv.prodAssoc
#check abs_integral_le_integral_abs
#check norm_integral_le_of_norm_le
#check MeasureTheory.integral_mono_ae
#check MeasureTheory.norm_integral_le_integral_norm
#check MeasureTheory.norm_integral_le_of_norm_le_const
#check MeasureTheory.integral_abs
#check MeasureTheory.continuousAt_of_dominated
#check MeasureTheory.continuous_of_dominated
#check MeasureTheory.tendsto_integral_filter_of_dominated_convergence
#check MeasureTheory.tendsto_setIntegral_filter_of_dominated_convergence
