name = "perceptronFixed"
packagesDir = "../.lake/packages"
buildDir = "../.lake/build"
defaultTargets = ["perceptronFixed"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.26.0"

[[lean_lib]]
name = "perceptronFixed"
srcDir = ".."
globs = ["perceptronFixed.+"]
